services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge