# Generated by Django 4.2.19 on 2025-02-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('renda_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locatario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.locatario')),
            ],
        ),
    ]
